name: .NET Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: restore dependencies
        run: dotnet restore src/**/*.csproj
      - name: Build
        run: dotnet build src/**/*.csproj --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test tests/**/*.csproj --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack src/**/*.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push *.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
